#!/bin/sh
set -eu

appdir="${APPDIR:-$(dirname "$(readlink -f "$0")")}"

export APPDIR="${appdir}"
export PATH="${appdir}/usr/bin:${PATH:-}"
export Z3R_LAUNCHER_REQUIRE_WEBVIEW=1
export Z3R_LAUNCHER_WEBVIEW_GUI=gtk
export PYWEBVIEW_GUI=gtk
typelib_path=""

for libdir in "${appdir}/usr/lib/"*-linux-gnu; do
  if [ -d "${libdir}" ]; then
    export LD_LIBRARY_PATH="${libdir}:${appdir}/usr/lib:${LD_LIBRARY_PATH:-}"
    export GDK_PIXBUF_MODULEDIR="${libdir}/gdk-pixbuf-2.0/2.10.0/loaders"
    export GDK_PIXBUF_MODULE_FILE="${libdir}/gdk-pixbuf-2.0/2.10.0/loaders.cache"
    if [ -d "${libdir}/girepository-1.0" ]; then
      typelib_path="${libdir}/girepository-1.0"
    fi
    break
  fi
done

if [ -d "${appdir}/usr/lib/girepository-1.0" ]; then
  if [ -n "${typelib_path}" ]; then
    typelib_path="${typelib_path}:${appdir}/usr/lib/girepository-1.0"
  else
    typelib_path="${appdir}/usr/lib/girepository-1.0"
  fi
fi

if [ -n "${typelib_path}" ]; then
  export GI_TYPELIB_PATH="${typelib_path}${GI_TYPELIB_PATH:+:${GI_TYPELIB_PATH}}"
fi

export XDG_DATA_DIRS="${appdir}/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

if [ -d "${appdir}/usr/share/glib-2.0/schemas" ]; then
  export GSETTINGS_SCHEMA_DIR="${appdir}/usr/share/glib-2.0/schemas"
fi

if [ -f "${appdir}/usr/etc/fonts/fonts.conf" ]; then
  export FONTCONFIG_PATH="${appdir}/usr/etc/fonts"
  export FONTCONFIG_FILE="${appdir}/usr/etc/fonts/fonts.conf"
fi

exec "${appdir}/usr/bin/z3r-launcher" "$@"
